const bookTypes = {
  // GET BOOKS
  GET_BOOKS_START: 'GET_BOOKS_START',
  GET_BOOKS_SUCCESS: 'GET_BOOKS_SUCCESS',
  GET_BOOKS_FAILURE: 'GET_BOOKS_FAILURE',

  // GET BOOK
  GET_BOOK_START: 'GET_BOOK_START',
  GET_BOOK_SUCCESS: 'GET_BOOK_SUCCESS',
  GET_BOOK_FAILURE: 'GET_BOOK_FAILURE',

  // GET FILTER
  GET_FILTER_START: 'GET_FILTER_START',
  GET_FILTER_SUCCESS: 'GET_FILTER_SUCCESS',
  GET_FILTER_FAILURE: 'GET_FILTER_FAILURE',

  // CLEAR BOOK
  CLEAR_BOOK: 'CLEAR_BOOK',

  // CLEAR BOOKS
  CLEAR_BOOKS: 'CLEAR_BOOKS'
};

export default bookTypes;
