const bookTypes = {
  // GET ALL BOOKS
  GET_ALL_BOOKS_START: 'GET_ALL_BOOKS_START',
  GET_ALL_BOOKS_SUCCESS: 'GET_ALL_BOOKS_SUCCESS',
  GET_ALL_BOOKS_FAILURE: 'GET_ALL_BOOKS_FAILURE',

  // GET BOOK
  GET_BOOK_START: 'GET_BOOK_START',
  GET_BOOK_SUCCESS: 'GET_BOOK_SUCCESS',
  GET_BOOK_FAILURE: 'GET_BOOK_FAILURE',
};

export default bookTypes;
