const bookTypes = {
  // GET BOOKS
  GET_BOOKS_START: 'GET_BOOKS_START',
  GET_BOOKS_SUCCESS: 'GET_BOOKS_SUCCESS',
  GET_BOOKS_FAILURE: 'GET_BOOKS_FAILURE',

  // GET BOOK
  GET_BOOK_START: 'GET_BOOK_START',
  GET_BOOK_SUCCESS: 'GET_BOOK_SUCCESS',
  GET_BOOK_FAILURE: 'GET_BOOK_FAILURE',

  // GET BOOKS BY PUBLISHER
  GET_BOOKS_BY_PUBLISHER_START: 'GET_BOOKS_BY_PUBLISHER_START',
  GET_BOOKS_BY_PUBLISHER_SUCCESS: 'GET_BOOKS_BY_PUBLISHER_SUCCESS',
  GET_BOOKS_BY_PUBLISHER_FAILURE: 'GET_BOOKS_BY_PUBLISHER_FAILURE',

  // GET FILTER
  GET_FILTER_START: 'GET_FILTER_START',
  GET_FILTER_SUCCESS: 'GET_FILTER_SUCCESS',
  GET_FILTER_FAILURE: 'GET_FILTER_FAILURE',

  // SET PARAMS FOR FILTER
  SET_PARAMS_FOR_FILTER: 'SET_PARAMS_FOR_FILTER',

  // GET COUNT BOOKS
  GET_COUNT_BOOKS: 'GET_COUNT_BOOKS',
  RESET_COUNT_BOOKS: 'RESET_COUNT_BOOKS',

  // CLEAR BOOK
  CLEAR_BOOK: 'CLEAR_BOOK',

  // CLEAR BOOKS
  CLEAR_BOOKS: 'CLEAR_BOOKS'
};

export default bookTypes;
