const profileTypes = {
  // GET ALL USERS
  GET_ALL_USERS_START: 'GET_ALL_USERS_START',
  GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
  GET_ALL_USERS_FAILURE: 'GET_ALL_USERS_FAILURE',

  // GET USER
  GET_USER_START: 'GET_USER_START',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',

  // CLEAR USERS
  CLEAR_USERS: 'CLEAR_USERS',
  CLEAR_USER: 'CLEAR_USER'
};

export default profileTypes;
