const authorTypes = {
  // GET ALL AUTHORS
  GET_ALL_AUTHORS_START: 'GET_ALL_AUTHORS_START',
  GET_ALL_AUTHORS_SUCCESS: 'GET_ALL_AUTHORS_SUCCESS',
  GET_ALL_AUTHORS_FAILURE: 'GET_ALL_AUTHORS_FAILURE',

  // GET AUTHOR
  GET_AUTHOR_START: 'GET_AUTHOR_START',
  GET_AUTHOR_SUCCESS: 'GET_AUTHOR_SUCCESS',
  GET_AUTHOR_FAILURE: 'GET_AUTHOR_FAILURE',

  // CLEAR
  CLEAR_AUTHORS: 'CLEAR_AUTHORS',
  CLEAR_AUTHOR: 'CLEAR_AUTHOR'
};

export default authorTypes;
